server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:
        # Auth Service Route (Public)
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        # Account Service Route (Secured)
        - id: account-service-route
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        # Transaction Service Route (Secured)
        - id: transaction-service-route
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
management:
  endpoint:
    health:
      show-details: always